/**********************************************************************
 * Extern for ScrollMagic
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ScrollMagic = {
  "Controller": {
    "addOption": function () {},
    "extend": function () {}
  },
  "Event": function () {},
  "Scene": {
    "addOption": function () {},
    "extend": function () {}
  },
  "_util": {
    "addClass": function () {},
    "cAF": function () {},
    "css": function () {},
    "extend": function () {},
    "get": {
      "elements": function () {},
      "height": function () {},
      "offset": function () {},
      "scrollLeft": function () {},
      "scrollTop": function () {},
      "width": function () {}
    },
    "isMarginCollapseType": function () {},
    "log": function () {},
    "rAF": function () {},
    "removeClass": function () {},
    "type": {
      "Array": function () {},
      "DomElement": function () {},
      "Function": function () {},
      "Number": function () {},
      "String": function () {}
    }
  },
  "version": {}
};
ScrollMagic.Scene.prototype = {
  "addIndicators": function () {},
  "removeIndicators": function () {},
  "removeTween": function () {},
  "removeVelocity": function () {},
  "setTween": function () {},
  "setVelocity": function () {}
};
/**********************************************************************
 * End Generated Extern for ScrollMagic
/**********************************************************************/
