(ns calfresh-minisite.quotes)

(def quotes
  {
   "Alameda" ["I'm currently enrolled at UC Berkeley but my finances are very tight."
              "I'm struggling really bad, to the point of being in debt."
              "The rent is extremely high here and we receive absolutely no financial assistance from our parents"]
   "Alpine" []
   "Amador" []
   "Butte" []
   "Calaveras" []
   "Colusa" []
   "Contra Costa" ["I need help with many basic day to today activities of daily living, because im disabled and have great difficulty getting things done"
                   "I was fired. In December I borowed from my 401K to pay off credit card debit, which I did. "]
   "Del Norte" []
   "El Dorado" []
   "Fresno" []
   "Glenn" []
   "Humboldt" []
   "Imperial" []
   "Inyo" []
   "Kern" []
   "Kings" []
   "Lake" []
   "Lassen" []
   "Los Angeles" []
   "Madera" []
   "Marin" ["I'm an unpaid intern working in Marin county for 6 months to complete my internship course credit for school"
            "I'm a single mom, divorced from someone that was highly abusive-mentally and physically."]
   "Mariposa" []
   "Mendocino" []
   "Merced" []
   "Modoc" []
   "Mono" []
   "Monterey" []
   "Napa" []
   "Nevada" []
   "Orange" []
   "Placer" []
   "Plumas" []
   "Riverside" []
   "Sacramento" []
   "San Benito" []
   "San Bernardino" []
   "San Diego" []
   "San Francisco" ["I work for a non-profit in San Francisco and I live in Oakland; therefore a big portion of my paycheck goes to transportation (roughly $360) a month."
                    "I am currently going to college as a full time student, and I do not have full financial aid coverage"
                    "Disability was declined. I really need help for food and other basic necessities."
                    ]
   "San Joaquin" []
   "San Luis Obispo" []
   "San Mateo" []
   "Santa Barbara" []
   "Santa Clara" []
   "Santa Cruz" []
   "Shasta" []
   "Sierra" []
   "Siskiyou" []
   "Solano" []
   "Sonoma" []
   "Stanislaus" []
   "Sutter" []
   "Tehama" []
   "Trinity" []
   "Tulare" []
   "Tuolumne" []
   "Ventura" []
   "Yolo" []
   "Yuba" []
   }
)
